[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-8_x"]

[phases.install]
cmds = ["npm ci --omit=dev"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmds = ["mkdir -p server/data", "touch server/data/leads.json", "npm run start"]
