# Render Blueprint Configuration
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: maddy-web
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true

